version: "3.9"

services:
  diabot:
    build:
      context: .
      dockerfile: Dockerfile
    image: diabot/app:local
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      # Cho phép override nhanh nếu cần
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/api/qa/selftest"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

  # Native Postgres service (replaces Supabase runtime)
  db:
    image: postgres:15
    container_name: diabot-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: diabot
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d diabot"]
      interval: 10s
      timeout: 5s
      retries: 5
