version: "3.9"

# DIABOT Production Docker Compose Configuration
# Environment: Viettel Cloud VPS Staging
# Version: 0.9.0
# Port: 80 (mapped from container port 3000)

services:
  diabot:
    build:
      context: .
      dockerfile: Dockerfile
    image: diabot/app:0.9.0
    container_name: diabot-staging
    ports:
      - "80:3000"
    env_file:
      - .env.production
    environment:
      # Override settings for production deployment
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/api/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - diabot-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

networks:
  diabot-network:
    driver: bridge
    name: diabot-staging-network

# Volume configuration (if needed in future)
# volumes:
#   diabot-data:
#     driver: local
